name: Build and Push Docker Image

on:
  push:
    branches: [ main ] # Запуск при пуше в main
    tags:
      - 'v*.*.*' # Запуск при создании тега вида v1.2.3

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write # Права на запись в GitHub Packages (GHCR)

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }} # Стандартный токен GitHub Actions

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }} # Имя образа: ghcr.io/your_username/your_project_name
          tags: |
            # type=schedule # Тег latest при ежедневной сборке (если нужно)
            type=ref,event=branch # Тег 'main' для ветки main
            type=ref,event=tag # Тег версии для Git-тегов (v1.2.3 -> 1.2.3)
            type=sha # Тег с commit SHA (например, sha-a1b2c3d)

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha # Использовать кэш GitHub Actions
          cache-to: type=gha,mode=max